configuration :
- name : alice
  ip   : 127.0.0.1
  port : 8081
- name : bob
  ip   : 127.0.0.1
  port : 8082
- name : charlie
  ip   : 127.0.0.1
  port : 8083
- name : daphnie
  ip   : 127.0.0.1
  port : 8084
- name : fred
  ip   : 127.0.0.1
  port : 8085

# This is the incoming port on which MP will listen
# May be changed for further communication as usual

sendRules :
  - action : send
    src : nobody

receiveRules :
  - action : send
    src : nobody

groups :
  - name: Group 1
    members :
    - alice
    - bob
    - charlie
  - name: Group 2
    members :
    - fred
    - daphnie