configuration :
- name : alice
  ip   : 127.0.0.1
  port : 8081
- name : bob
  ip   : 127.0.0.1
  port : 8082
- name : charlie
  ip   : 127.0.0.1
  port : 8083
- name : daphnie
  ip   : 127.0.0.1
  port : 8084
- name : fred
  ip   : 127.0.0.1
  port : 8085

# This is the incoming port on which MP will listen
# May be changed for further communication as usual

sendRules :
  - action : send
    src : nobody

receiveRules :
  - action : drop
    src : bob
    dest : alice
    seqNum : 0
  - action : drop
    src : bob
    dest : alice
    seqNum : 1
  - action : drop
    src : bob
    dest : alice
    seqNum : 2
  - action : drop
    src : bob
    dest : alice
    seqNum : 3
  - action : drop
    src : bob
    dest : alice
    seqNum : 4
  - action : drop
    src : bob
    dest : alice
    seqNum : 5
  - action : drop
    src : bob
    dest : alice
    seqNum : 6
  - action : drop
    src : bob
    dest : alice
    seqNum : 7
  - action : drop
    src : bob
    dest : alice
    seqNum : 8


groups :
  - name: Group 1
    members :
    - alice
    - bob
    - charlie
  - name: Group 2
    members :
    - fred
    - daphnie